apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-controller
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: public.ecr.aws/l0g8r8j6/fluxcd/source-controller:v1.2.1-eks-a-v0.0.0-dev-build.7944
        name: manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: public.ecr.aws/l0g8r8j6/fluxcd/kustomize-controller:v1.1.1-eks-a-v0.0.0-dev-build.7930
        name: manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-controller
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: public.ecr.aws/l0g8r8j6/fluxcd/helm-controller:v0.36.2-eks-a-v0.0.0-dev-build.7930
        name: manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-controller
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: public.ecr.aws/l0g8r8j6/fluxcd/notification-controller:v1.2.1-eks-a-v0.0.0-dev-build.7943
        name: manager